### PR TITLE
The "Get Involved" Email Blast

### PR DESCRIPTION
**Pull request by Perksey**
This is an email put together for all .NET Foundation members to raise awareness of how they can help out in shaping the .NET Foundation, and hopefully encourage "passive" members to become more active within the .NET Foundation.

The opening of the email describes how the .NET Foundation operates and what it means to be a member, as well as how members can get involved (i.e. committees). This is meant to be the "persuasive" bit of the email, so let me know if there's any way I can improve this.

After that, the email describes each of the active committees. I've structured this in terms of what a committee member could be doing (i.e. using "you" a lot, sort of like a job description) to hopefully make it obvious what the committee is doing.

For committees that didn't have an obvious joining mechanism, I've linked them to the discussions repo. Otherwise, the "how to join" bit is copied and pasted from the working group repos, as with the meeting dates and other parts of the content.

The committee are in order from the most project-centric committees to the most people-centric committees, so the committees most likely to be relevant depending on a particular member's interests are bundled close together.

Let me know what you think.

### CODE REVIEW

**Comment by Perksey** [comment]
Paging committee chairpersons just in case I've got anything wrong.
- [ ] **Projects**:  @sbwalker
- [ ] **Maintainers**: @devlead @rprouse 
- [ ] **Outreach**: @shawnwildermuth 
- [ ] **Marketing**: @isaacrlevin 
- [ ] **Education**: @bjablonsky
- [ ] **Membership**: @BillWagner

**Comment by Perksey** [comment]
Note @dotnet-foundation/directors is the Board still interested in pushing the Corporate Sponsorship/Relations committee? It seems this doesn't have a chairperson currently and hasn't had a proper kick-off. I can include it in this email, but perhaps if this committee is still of interest it'd be better for its own, dedicated "we want to make a new committee!" email?

**Comment by jglozano** [comment]
- [ ] Hi! I'm the chair for Corp Sponsorship committee. I took the position in Oct and had our first meeting in Nov.

**Comment by Perksey** [comment]
Oh hey, apologies! Missed that in the GitHub repo! I'll write some words on that now, can you chime in on the meeting schedule as well as how to join?

**Comment by jglozano** [comment]
> Oh hey, apologies! Missed that in the GitHub repo! I'll write some words on that now, can you chime in on the meeting schedule as well as how to join?

Yep! I'm out right now but can provide details later today

**Comment by sbwalker** [comment]
Note that I am stepping down as Chair of the Projects Committee - and none of the current members have volunteered to take over the role. The future of the Project Committee is uncertain at this stage so I would recommend not including it in the newsletter.

**Comment by isaacrlevin** [comment]
@bjablonsky is no longer the chair of the education committee, that seat is currently open

**Comment by jglozano** [comment]
> > Oh hey, apologies! Missed that in the GitHub repo! I'll write some words on that now, can you chime in on the meeting schedule as well as how to join?
> 
> Yep! I'm out right now but can provide details later today

@Perksey my apologies for taking this long to respond but I didn't have time at all with all the driving I did this weekend.

Meeting cadence, it's the 3rd Wed of every month from 1-2pm ET. I'm still working on the GH repo so for now, since we have something out there that needs some TLC - https://github.com/dotnet-foundation/wg-corporate-relations

For now, it's best if people can email me at javier.lozano@dotnetfoundation.org and I can add them.

**Comment by shawnwildermuth** [comment]
@CalvinAllen - we can take this offline here, but committee chairs do not have to be board members so this is possible. I just didn't want to divert this conversation.

**Comment by Perksey** [comment]
I've removed the joining info and meeting cadence from the Projects and Education committees in response to the feedback (I figured we should still put their descriptions in the email for full transparency!)

Let me know what you all think (and let me know if you're happy as well :P), would be good to be able to send this out soon!

**Pull request merged**
